---
- name: Edit all nameservers to a specific one.
  hosts: all,!netboot
  become: true
  tasks:
    - name: Change nameserver
      ansible.builtin.replace:
        path: /etc/resolv.conf
        regexp: 'nameserver 10.0.0.1.*'
        replace: 'nameserver 10.0.0.114'