# This playbook needs an user with sudo or root. For example:
#
# ansible-playbook add_public_keys.yaml -u justin -k -K

---
- name: Initial Configuration for Debian Server
  hosts: initial
  become: true
  tasks:
    - name: Create user
      ansible.builtin.user:
        name: ansible
        comment: Ansible user
        groups: "sudo"
        append: true
    - name: Edit sudoers file for initial group
      community.general.sudoers:
        name: ansible-all-rights
        state: present
        user: ansible
        commands: ALL
        nopassword: true
    - name: Install public keys
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '~/.ssh/ansible_id_rsa.pub') }}"
    - name: Install qemu agent
      ansible.builtin.package:
        name: qemu-guest-agent
        state: present
